name: "Credly Badges"

on:
  schedule:
    - cron: "0 14 * * *"

jobs:
  credly-badges:
    name: "Update README with Credly badges"
    runs-on: ubuntu-latest

    steps:
      - name: Update
        uses: AndrewRiddoch/credly-badges@main
        with:
          CREDLY_USERNAME: andrew-riddoch
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_MESSAGE: "Update Credly badges!"
...
on:
  push:
...
